version: '3.8'

services:
  db:
    image: postgres:16
    container_name: geoviewer_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

